const axios = require("axios");

async function createPlaylistAndExport({
  token,
  userId,
  name,
  trackIds,
}) {
  const headers = {
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
  };

  // 1. CREATE PLAYLIST
  const createRes = await axios.post(
    `https://api.spotify.com/v1/users/${userId}/playlists`,
    {
      name,
      description: "Generated by Audio-Draft",
      public: false,
    },
    { headers }
  );

  const playlistId = createRes.data.id;
  console.log("Created playlist:", playlistId);

  // 2. ADD TRACKS (Spotify limit: 100 per request)
  for (let i = 0; i < trackIds.length; i += 100) {
    const chunk = trackIds.slice(i, i + 100);

    await axios.post(
      `https://api.spotify.com/v1/playlists/${playlistId}/tracks`,
      {
        uris: chunk.map(id => `spotify:track:${id}`),
      },
      { headers }
    );
  }

  console.log("Export complete ✅");
}

module.exports = createPlaylistAndExport;


 